@startuml

title __DB's Class Diagram__\n

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.AccountBean {
          ~ beizhu : String
          ~ day : int
          ~ id : int
          ~ kind : int
          ~ money : int
          ~ month : int
          ~ sImageId : int
          ~ time : String
          ~ typename : String
          ~ year : int
          + AccountBean()
          + AccountBean()
          + getBeizhu()
          + getDay()
          + getId()
          + getKind()
          + getMoney()
          + getMonth()
          + getTime()
          + getTypename()
          + getYear()
          + getsImageId()
          + setBeizhu()
          + setDay()
          + setId()
          + setKind()
          + setMoney()
          + setMonth()
          + setTime()
          + setTypename()
          + setYear()
          + setsImageId()
      }
    }
  }
  

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.BarChartItemBean {
          ~ day : int
          ~ month : int
          ~ summoney : float
          ~ year : int
          + BarChartItemBean()
          + BarChartItemBean()
          + getDay()
          + getMonth()
          + getSummoney()
          + getYear()
          + setDay()
          + setMonth()
          + setSummoney()
          + setYear()
      }
    }
  }
  

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.ChartItemBean {
          ~ Type : String
          ~ ratio : float
          ~ sImageId : int
          ~ totalMoney : float
          + ChartItemBean()
          + ChartItemBean()
          + getRatio()
          + getTotalMoney()
          + getType()
          + getsImageId()
          + setRatio()
          + setTotalMoney()
          + setType()
          + setsImageId()
      }
    }
  }
  

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.DBManager {
          {static} - db : SQLiteDatabase
          {static} + deleteAllAccount()
          {static} + deleteItemFromAccounttbById()
          {static} + getAccountListByRemarkFromAccounttb()
          {static} + getAccountListOneDayFromAccounttb()
          {static} + getAccountListOneMonthFromAccounttb()
          {static} + getChartListFromAccounttb()
          {static} + getCountItemOneMonth()
          {static} + getMaxMoneyOneDay()
          {static} + getSumMoneyOneDay()
          {static} + getSumMoneyOneDayInMonth()
          {static} + getSumMoneyOneMonth()
          {static} + getSumMoneyOneYear()
          {static} + getTypeList()
          {static} + getYearListFromAccounttb()
          {static} + initDB()
          {static} + insertItemToAccounttb()
      }
    }
  }
  

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.DBOpenHelper {
          + DBOpenHelper()
          + onCreate()
          + onUpgrade()
          - insertAccount()
          - insertType()
      }
    }
  }
  

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.PieChartItemBean {
          ~ Type : String
          ~ day : int
          ~ month : int
          ~ ratio : float
          ~ totalMoney : float
          ~ year : int
          + PieChartItemBean()
          + PieChartItemBean()
          + getDay()
          + setDay()
      }
    }
  }
  

  namespace com.example.csufttally {
    namespace db {
      class com.example.csufttally.db.TypeBean {
          ~ id : int
          ~ imageId : int
          ~ kind : int
          ~ sImageId : int
          ~ typename : String
          + TypeBean()
          + TypeBean()
          + getId()
          + getImageId()
          + getKind()
          + getSimageId()
          + getTypename()
          + setId()
          + setImageId()
          + setKind()
          + setSimageId()
          + setTypename()
      }
    }
  }
  

  com.example.csufttally.db.DBOpenHelper -up-|> android.database.sqlite.SQLiteOpenHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
